### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SbaoNaoki** [enpitut2023/IE_teacher#43]
https://iesensei.haruki1.repl.co/papers/a992c8fd24587f12d41f48df84b29d847634c0e4-90485e0ce54c1ad12a2d01362a007ab107d71063
から
[BioJava: an open-source framework for bioinformatics](https://iesensei.haruki1.repl.co/papers/a992c8fd24587f12d41f48df84b29d847634c0e4-90485e0ce54c1ad12a2d01362a007ab107d71063-05aa2c49c418d2dc099cc945b6f51a845a6a316a)
をクリックするとErrorが表示される。

**Comment by DoiRyoto** [comment]
原因：取得した論文リストにNoneが含まれた
解決方法：Noneを弾く処理を加えた
